validators:
  - field: rename_repository_current_name
    script: repository-exists-true.js
  - field: rename_repository_new_name
    script: repository-name-valid-true.js
  - field: rename_repository_new_name
    script: repository-exists-false.js
