name: '[IssueOps] Unarchive Repository'
description: Unarchive a repository in your organization.
title: '[IssueOps] Unarchive Repository'
labels:
  - issue-ops
  - unarchive-repository
body:
  - id: unarchive_repository_organization
    type: input
    attributes:
      label: GitHub Organization
      description: GitHub organization where the repository is located
      placeholder: github
    validations:
      required: true
  - id: unarchive_repository_name
    type: input
    attributes:
      label: GitHub Repository
      description: GitHub repository name
      placeholder: monarepo
    validations:
      required: true
